name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --html=pytest_report.html

    - name: Lint code
      run: |
        flake8 --format=html --htmldir=flake8_report

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: pytest_report.html

    - name: Upload lint report
      uses: actions/upload-artifact@v2
      with:
        name: lint-reports
        path: flake8_report
